### ISSUE TITLE
Privet

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [mokuteki225/nest-anime-tracker#22]
Ti ne protiv, elsi ya vozmu i sdelaiu s tvoim app some magic(DevOps)?

**Comment by vkondratiuk482** [comment]
Would be great, you can also make a PR when it's done!

**Comment by Arkady-Skvortsov** [comment]
Ok than

**Comment by Arkady-Skvortsov** [comment]
I would send a new PR so soon as I can)

**Comment by Arkady-Skvortsov** [comment]
Have you a telegram?);
