### ISSUE TITLE
[FEATURE] Critica

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [mokuteki225/nest-anime-tracker#3]
О привет, в общем, у тебя оч не понятный код с точки зрения того, что у тебя один и тот же енум(это я по быстрому ещё глянул) было 2 файла его и лежал один в сервисе A, а другой в B (у тебя же все равно 2 сервиса); Я бы просто вынес в отдельную папку за эти 2 микросервиса, чтобы это все переиспользовать, потом бы я взял бы и придумал какую-нибудь бизнес модель, на которую очень хорошо легли бы микросервисы; Построил бы сначала монолит и потом бы начал проводить границы, тестировать их и в конечном счете из модульного монолита родились бы микросервисы; Попробуй с модульного монолита;

**Comment by Arkady-Skvortsov** [comment]
Ну тоесть я имею ввиду возьми свой монолит, проведи границы ему и поставь к этим блокам проход через брокеры(Kafka таже) и у тебя уже 2 - 3 канала по которым общаются твои сервисы и они пока что ещё они в монолите(P.S одна база данных) и уже потом когда понятно что сервис A прямо 100% отдает данные сервису B а тот идет в сервис C(ну ты меня понял); Тогда уже можешь делать микросервисы и вауаля

Готово

**Comment by vkondratiuk482** [comment]
thank you! I'll try to take everything you said into consideration!
